---
title: "QMSS G5072 Homework 2"
author: Thomas Brambor
date: 2017-09-21
always_allow_html: yes
output: 
  html_document:
    keep_md: true
---

Data Wrangling
============================

The objective of this assignment is to wrangle a data set, produce some summary statistics, and visualize the correlation between binge drinking prevalence and poverty in U.S. States. 

## Data

The data we want to use are the [U.S. Chronic Disease Indicators (CDI)](https://catalog.data.gov/dataset/u-s-chronic-disease-indicators-cdi-e50c9). Download the data in .xls format.

## Selection of Data and Tidying

The data contains lots of indicators and is in a non-tidy format. 

1. Remove all columns you do not need for the analysis. 
2. We are interested in two sets of variables. Select the following variables and remove all others:
    a) **Binge Drinking**:
    _Binge drinking prevalence among adults aged >= 18 years_, Crude Prevalence in Percent. 
    We would like to obtain this variable for the overall population, as well separately for _females_ and _males_.
    b) **Poverty**:
    _Poverty, Crude Prevalence in Percent_. We only want the overall poverty prevalence to make things a bit easier.
3. Convert the dataset to a tidy data set using the commands from the `tidyr` package.
4. Rename the variables to follow the format below.

Your dataset should now be in a tidy state-year format with the following variables:  
  - `state`: Name of the State  
  - `stateabb`: State Abbreviation  
  - `year`: year of observation  
  - `binge_all`: Binge drinking prevalence among _all_ adults aged >= 18 years  
  - `binge_male`: Binge drinking prevalence among _male_ adults aged >= 18 years  
  - `binge_female`: Binge drinking prevalence among _female_ adults aged >= 18 years  
  - `poverty`: Poverty, Crude Prevalence in Percent  
  
Save the cleaned dataset as `binge_clean.csv`.

## Data Transformation and Summary Results

5. Produce a table that shows the overall, female, and male binge drinking prevalences across U.S. States in the most recent year of data for the Top 10 binge drinking states (i.e. the ones with the highest prevalence in the overall population). Use the relevant `dplyr` commands to `select` the right variables, sort the data (`arrange()`), and `filter` the data frame.

6. Make a simple scatter plot showing the correlation between the overall poverty prevalence in a state and the prevalence of binge drinking in the overall population. I suggest to [use `ggplot`](http://www.cookbook-r.com/Graphs/Scatterplots_(ggplot2)/). Add a loess smoothed fit curve (use `geom_smooth` in the `ggplot2` package) to indicate the pattern. Comment briefly.

7. Calculate the average annual growth rates (in percent) of overall binge drinking across states for the years the data is available. One way to get these growth rates, is to group the data by state (`dplry::group_by`) and use the `first()` and `last()` commands in the `summarize` command followed by dividing the calculated percentage increase by the number of years. Provide a table of the _5 states with the largest increases_ and the _5 states with the largest decreases_ in binge drinking prevalence over the time period. 

## Submission

Please follow the [instructions](/Exercises/homework_submission_instructions.md) to submit your homework. The homework is due on Monday, September 25.

Please do **not** include the original full data set in your submission. Add the file to your `.gitignore` file or in the GitHub Desktop App right-click on the data file and choose "ignore" to prevent the data from being uploaded. Do include the cleaned dataset `binge_clean.csv` however.
